from .IndexView import *
from .BookView import *
from .BookInstanceView import *
from .AuthorView import *
from .AuthorDtView import *
from .LoanView import *
from .AllBrorrowedView import *
from .AuthorCrudView import *
from .BookCrudView import *
