# Generated by Django 3.2.3 on 2021-05-29 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Informe um nome de idioma (ex. Francês)', max_length=200, verbose_name='Nome')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.ForeignKey(help_text='Informe o idioma em que foi escrito o livro', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.language', verbose_name='Idioma'),
        ),
    ]
