# Generated by Django 3.2.3 on 2021-06-12 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20210611_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Definir livro como devolvido'),), 'verbose_name': 'Exemplar', 'verbose_name_plural': 'Exemplares'},
        ),
    ]
